"""Generate data/transliteration_variants.json from data/transliteration.json.

The base table has one or a few spellings per entry; this adds the other common Latin spellings
(search/translit_variants.py: al-/el-/an-, -ah/-a, ee/i, oo/u, u/o, doubled letters, q/k, d/dh, ...).

A generated spelling is dropped when it
  - is already a key of the base table (the base table always wins),
  - comes from two entries with different meanings,
  - is an ordinary English word: it appears in lowercase in the corpus English translations
    (the old "sad" -> surah Sad, "will" -> الوصية kind of collision),
  - is shorter than 4 letters.

It also lists the base keys that are ordinary English words the translations use ("patience", "zakat"):
the classifier keeps those in the query and adds the Arabic after them.

Re-run after editing data/transliteration.json:
    python build_transliteration_variants.py
"""
import collections
import json
import re

from config import CORPUS_MAP_FILE, TRANSLITERATION_FILE, TRANSLITERATION_VARIANTS_FILE
from search.translit_variants import latin_variants
from search.constants import TRANSLIT_KEEP_ENGLISH

OUT_FILE= TRANSLITERATION_VARIANTS_FILE
ENGLISH_WORD_MIN_COUNT= 3      # lowercase occurrences in the translations to count as an English word
KEEP_ENGLISH_MIN_COUNT= 20     # a base key used this often in the translations is kept in the query
MIN_VARIANT_LETTERS= 4


def english_vocabulary(corpus: list[dict]) -> tuple[collections.Counter, collections.Counter, collections.Counter]:
    """Lowercase word / bigram / trigram counts of the English translations (capitalised names excluded)."""
    unigrams, bigrams, trigrams= collections.Counter(), collections.Counter(), collections.Counter()
    seen= set()
    for chunk in corpus:
        text= chunk.get("english_text", "")
        if not text or text in seen:
            continue
        seen.add(text)
        words= re.findall(r"[A-Za-z][A-Za-z'\-]*", text)
        unigrams.update(w for w in words if w.islower())
        bigrams.update(f"{a} {b}" for a, b in zip(words, words[1:]))
        trigrams.update(f"{a} {b} {c}" for a, b, c in zip(words, words[1:], words[2:]))
    return unigrams, bigrams, trigrams


def main():
    base= json.load(open(TRANSLITERATION_FILE, encoding="utf-8"))
    base= {k.lower().strip(): v for k, v in base.items() if v and not k.startswith("___")}
    corpus= json.load(open(CORPUS_MAP_FILE, encoding="utf-8"))
    unigrams, bigrams, trigrams= english_vocabulary(corpus)

    def english_count(phrase: str) -> int:
        n= len(phrase.split())
        return {1: unigrams, 2: bigrams, 3: trigrams}.get(n, collections.Counter()).get(phrase, 0)

    keep_english= sorted(k for k in base if re.fullmatch(r"[a-z' \-]+", k) and english_count(k) >= KEEP_ENGLISH_MIN_COUNT)
    keep_all= set(keep_english) | TRANSLIT_KEEP_ENGLISH

    def is_english(phrase: str) -> bool:
        words= re.split(r"[\s\-]+", phrase)
        return all(unigrams.get(w, 0) >= ENGLISH_WORD_MIN_COUNT for w in words if w)

    candidates= collections.defaultdict(set)    # variant -> {replacement}
    for key, value in base.items():
        if not re.fullmatch(r"[a-z'’` \-]+", key):
            continue
        # a variant of a word the translations use becomes "<that word> (<arabic>)"; of a canonical-English
        # value ("koran" -> "Quran") just that value; otherwise the Arabic
        has_arabic= bool(re.search(r"[؀-ۿ]", value))
        replacement= f"{key} ({value})" if (key in keep_all and has_arabic) else value
        # English words inside a phrase keep their spelling ("day of arafah": only "arafah" varies); a word that is
        # itself a transliteration ("zakat", "hajj" - the translations use them too) still varies
        words= [w for w in re.split(r"[\s\-]+", key) if w]
        english_words= frozenset(w for w in words if len(words) > 1 and w not in base
                                 and unigrams.get(w, 0) >= ENGLISH_WORD_MIN_COUNT)
        for variant in latin_variants(key, fixed_words=english_words):
            candidates[variant].add(replacement)

    variants, dropped= {}, collections.Counter()
    for variant, replacements in sorted(candidates.items()):
        letters= re.sub(r"[\s\-'’`]", "", variant)
        if variant in base:
            dropped["already a base key"] += 1
        elif len(replacements) > 1:
            dropped["ambiguous"] += 1
        elif len(letters) < MIN_VARIANT_LETTERS:
            dropped["too short"] += 1
        elif is_english(variant):
            dropped["english word"] += 1
        else:
            variants[variant]= next(iter(replacements))

    out= {"_note": "Generated by build_transliteration_variants.py from transliteration.json - do not edit by hand.",
          "keep_english": keep_english,
          "variants": variants}
    json.dump(out, open(OUT_FILE, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"base entries: {len(base)} | generated variants: {len(variants)} | keep-English keys: {len(keep_english)}")
    print("dropped:", dict(dropped))


if __name__== "__main__":
    main()
